import { createContext, useContext, useMemo, useState } from "react";

const STORAGE_KEY = "quizzer_language";

const translations = {
  en: {
    language: "Language",
    english: "EN",
    russian: "RU",
    back: "Back",
    next: "Next",
    submit: "Submit",
    save: "Save",
    room: "Room",
    loadingRoom: "Loading room",
    loadingQuiz: "Loading quiz",
    loadingResult: "Loading result",
    status_WAITING: "WAITING",
    status_STARTED: "STARTED",
    status_FINISHED: "FINISHED",
    status_CANCELLED: "CANCELLED",
    adminTitle: "Admin Dashboard",
    adminNavigation: "Admin navigation",
    adminSignInTitle: "Quizzer Admin",
    adminSignInSubtitle: "Sign in to create and manage quiz rooms.",
    createTest: "Create Test",
    tests: "Tests",
    setupRoom: "Set up room",
    createRoomSettings: "Room settings",
    createConfiguredRoom: "Create room",
    roomCreated: "Room created",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    refresh: "Refresh",
    logout: "Log Out",
    createRoom: "Create Room",
    questionsCount: "{count} questions",
    copyLink: "Copy Link",
    roomLink: "Room Link",
    settings: "Settings",
    roomLinkCopied: "Room link copied",
    settingsSaved: "Settings saved",
    start: "Start",
    finish: "Finish",
    startQuiz: "Start quiz",
    finishQuiz: "Finish quiz",
    closeRoom: "Close room",
    roomWaiting: "Room is waiting",
    liveQuiz: "Live quiz",
    quizFinished: "Quiz finished",
    hostConsole: "Host console",
    studentsJoinWithCode: "Students join with this code",
    joinAt: "Join at",
    copyCode: "Copy code",
    copyInviteLink: "Copy invite link",
    codeCopied: "Room code copied",
    inviteLinkCopied: "Invite link copied",
    quizSettings: "Quiz settings",
    passageParameters: "1. Completion parameters",
    scheduleSection: "2. Schedule",
    duration: "Duration",
    minutes: "minutes",
    timezone: "Timezone",
    roomSummary: "Room summary",
    testLabel: "Test",
    questionsSummary: "Questions",
    showAnswersSummary: "Show answers",
    backNavigationSummary: "Back to questions",
    yes: "Yes",
    no: "No",
    notSet: "Not set",
    lockedSettings: "Settings are locked while the quiz is live.",
    noSettingsChanges: "No unsaved changes",
    saveChanges: "Save changes",
    sessionStatus: "Session status",
    currentState: "Current state",
    scheduledFor: "Scheduled for",
    endsAtLabel: "Ends at",
    finalStatus: "Final status",
    online: "Online",
    offline: "Offline",
    completed: "Completed",
    joined: "Joined",
    noStudentsYet: "No students have joined yet.",
    noStudentsHelper: "Share the invite link or room code to start building the lobby.",
    progress: "Progress",
    finishConfirmTitle: "Finish quiz?",
    finishConfirmText: "Students will no longer be able to submit answers after you finish this room.",
    closeConfirmText: "This closes the room before the quiz starts. Students will not be able to join.",
    keepLive: "Cancel",
    confirmFinish: "Finish quiz",
    confirmClose: "Close room",
    finishedHelper: "The quiz is closed. Students can no longer submit answers.",
    showCorrectAnswers: "Show correct answers",
    allowBackNavigation: "Allow going back",
    durationSeconds: "Duration, seconds",
    scheduledStart: "Scheduled start",
    scheduledFinish: "Scheduled finish",
    starts: "Starts",
    ends: "Ends",
    participants: "Participants",
    noParticipants: "No participants yet",
    displayName: "Display name",
    joinRoom: "Join Room",
    manualStart: "Manual start",
    roomFinished: "This room is finished.",
    waitingTitle: "Waiting for admin to start the quiz",
    editName: "Edit name",
    cancel: "Cancel",
    nameSaved: "Name updated",
    questionProgress: "Question {current} of {total}",
    answeredProgress: "{count} of {total} answered",
    result: "Result",
    percentCorrect: "{percentage}% correct",
    selected: "Selected",
    correct: "Correct",
    answersSubmitted: "Your answers have been submitted",
    thankYou: "Thank you"
  },
  ru: {
    language: "Язык",
    english: "EN",
    russian: "RU",
    back: "Назад",
    next: "Далее",
    submit: "Отправить",
    save: "Сохранить",
    room: "Комната",
    loadingRoom: "Загрузка комнаты",
    loadingQuiz: "Загрузка теста",
    loadingResult: "Загрузка результата",
    status_WAITING: "ОЖИДАНИЕ",
    status_STARTED: "НАЧАТ",
    status_FINISHED: "ЗАВЕРШЕН",
    status_CANCELLED: "ОТМЕНЕН",
    adminTitle: "Панель администратора",
    adminNavigation: "Навигация администратора",
    adminSignInTitle: "Админ Quizzer",
    adminSignInSubtitle: "Войдите, чтобы создавать комнаты и управлять тестами.",
    createTest: "Создать тест",
    tests: "Тесты",
    setupRoom: "Настройка комнаты",
    createRoomSettings: "Настройки комнаты",
    createConfiguredRoom: "Создать комнату",
    roomCreated: "Комната создана",
    email: "Email",
    password: "Пароль",
    signIn: "Войти",
    refresh: "Обновить",
    logout: "Выйти",
    createRoom: "Создать комнату",
    questionsCount: "{count} вопроса",
    copyLink: "Копировать ссылку",
    roomLink: "Ссылка комнаты",
    settings: "Настройки",
    roomLinkCopied: "Ссылка скопирована",
    settingsSaved: "Настройки сохранены",
    start: "Старт",
    finish: "Завершить",
    startQuiz: "Начать тест",
    finishQuiz: "Завершить тест",
    closeRoom: "Закрыть комнату",
    roomWaiting: "Комната ожидает",
    liveQuiz: "Тест идет",
    quizFinished: "Тест завершен",
    hostConsole: "Панель ведущего",
    studentsJoinWithCode: "Студенты входят по этому коду",
    joinAt: "Ссылка для входа",
    copyCode: "Копировать код",
    copyInviteLink: "Копировать ссылку",
    codeCopied: "Код комнаты скопирован",
    inviteLinkCopied: "Ссылка приглашения скопирована",
    quizSettings: "Настройки теста",
    passageParameters: "1. Параметры прохождения",
    scheduleSection: "2. Расписание",
    duration: "Длительность",
    minutes: "минут",
    timezone: "Часовой пояс",
    roomSummary: "Сводка комнаты",
    testLabel: "Тест",
    questionsSummary: "Вопросов",
    showAnswersSummary: "Показывать ответы",
    backNavigationSummary: "Возврат к вопросам",
    yes: "Да",
    no: "Нет",
    notSet: "Не задано",
    lockedSettings: "Настройки заблокированы, пока тест идет.",
    noSettingsChanges: "Нет несохраненных изменений",
    saveChanges: "Сохранить изменения",
    sessionStatus: "Статус сессии",
    currentState: "Текущий статус",
    scheduledFor: "Запланировано на",
    endsAtLabel: "Закончится",
    finalStatus: "Итоговый статус",
    online: "Онлайн",
    offline: "Офлайн",
    completed: "Завершили",
    joined: "В комнате",
    noStudentsYet: "Студенты пока не подключились.",
    noStudentsHelper: "Отправьте ссылку приглашения или код комнаты.",
    progress: "Прогресс",
    finishConfirmTitle: "Завершить тест?",
    finishConfirmText: "После завершения комнаты студенты больше не смогут отправить ответы.",
    closeConfirmText: "Комната будет закрыта до старта. Студенты больше не смогут подключиться.",
    keepLive: "Отмена",
    confirmFinish: "Завершить тест",
    confirmClose: "Закрыть комнату",
    finishedHelper: "Тест закрыт. Студенты больше не могут отправлять ответы.",
    showCorrectAnswers: "Показывать правильные ответы",
    allowBackNavigation: "Разрешить возвращаться назад",
    durationSeconds: "Длительность, секунды",
    scheduledStart: "Запланированный старт",
    scheduledFinish: "Запланированное завершение",
    starts: "Старт",
    ends: "Финиш",
    participants: "Участники",
    noParticipants: "Участников пока нет",
    displayName: "Имя",
    joinRoom: "Войти в комнату",
    manualStart: "Ручной старт",
    roomFinished: "Комната уже завершена.",
    waitingTitle: "Ожидание старта теста администратором",
    editName: "Изменить имя",
    cancel: "Отмена",
    nameSaved: "Имя обновлено",
    questionProgress: "Вопрос {current} из {total}",
    answeredProgress: "{count} из {total} отвечено",
    result: "Результат",
    percentCorrect: "{percentage}% правильных",
    selected: "Выбрано",
    correct: "Правильно",
    answersSubmitted: "Ваши ответы отправлены",
    thankYou: "Спасибо"
  }
};

const LanguageContext = createContext(null);

function readLanguage() {
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "ru" || stored === "en" ? stored : "ru";
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(readLanguage);

  function setLanguage(nextLanguage) {
    const normalized = nextLanguage === "en" ? "en" : "ru";
    localStorage.setItem(STORAGE_KEY, normalized);
    setLanguageState(normalized);
  }

  function t(key, values = {}) {
    const template = translations[language][key] || translations.en[key] || key;
    return template.replace(/\{(\w+)\}/g, (_, name) =>
      values[name] === undefined ? `{${name}}` : String(values[name])
    );
  }

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return value;
}
